### ISSUE TITLE
Multiple first level resources?

### ISSUE THREAD

**Issue by cody-code-wy** [calvinmclean/babyapi#25]
Sorry if I am missing something, but it seems that the only way to have more than one resource is that they must be children of the first level recourse.

Is it possible to create an API with more than one completely independent resource currently?

**Comment by cody-code-wy** [comment]
Ok I realize I didn't fully understand the way that Chi routers worked, after re-reading the documentation I found a way. But I don't currently see a way in the current version that preserves the CLI functionality.

If this is the most idiomatic way to use this library then I can submit a PR with an added example using a Chi Router that routes multiple resources similar to the following code. This was just thrown together for testing so I would submit a PR that is more similar in code style and error handling to the existing examples.

`package main

import (
	"github.com/calvinmclean/babyapi"
	"github.com/go-chi/chi/v5"
	"net/http"
)

type TODO struct {
	babyapi.DefaultResource

	Name        string
	Description string
	Marked      bool
}

type GOAL struct {
	babyapi.DefaultResource

	Name        string
	Description string
	Complete    bool
}

func main() {
	TodoApi := babyapi.NewAPI[*TODO](
		"TODOs", "/todo",
		func() *TODO {
			return &TODO{}
		})
	GoalApi := babyapi.NewAPI[*GOAL](
		"GOALs", "/goals",
		func() *GOAL {
			return &GOAL{}
		})
	r := chi.NewRouter()
	TodoApi.Route(r)
	GoalApi.Route(r)
	err := http.ListenAndServe(":3000", r)
	if err != nil {
		return
	}
}`

**Comment by calvinmclean** [comment]
Hi @cody-code-wy, thanks for your interest in `babyapi`!

You are correct that this currently is the only way to run an API with multiple top-level resources. I previously had a function that was something like `babyapi.RunAll(babyapi.API...)` and would basically do what you did for a variable number of APIs. I removed it at some point; I think because it did not preserve CLI functionality like you mentioned.

I have this on my list of things to add, but am of course happy to accept contributions whether it is an example or new feature!
